output:
  dir: "C:/MyLibrary/Pytorch_Template/output/second_run"
  log_dir: "C:/MyLibrary/Pytorch_Template/output/second_run/logs"
  ckpt_dir: "C:/MyLibrary/Pytorch_Template/output/second_run/ckpt"
  img_dir: "C:/MyLibrary/Pytorch_Template/output/second_run/imgs"
Train:
  resume: True
  checkpoint_path: "C:/MyLibrary/Pytorch_Template/output/second_run/ckpt/best_at_00008000.tar"
  batch_size: 16
  val_steps: 1000
Infer:
  grid_cols: 8
  Imgs_per_grid: 64 